# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/research',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/research',
                'lib_path': 'research'},
  'syms': {'research.core': {'research.core.foo': ('core.html#foo', 'research/core.py')}}}
